### PR TITLE
[PE-D][Tester C] Country field validation incorrectly allows backslash (\) character

### LINKED ISSUE #410: [PE-D][Tester C] Country field validation incorrectly allows backslash (\) character
The Country field accepts inputs containing the backslash (\) character, even though this is not a valid character for country names and is not expected based on normal usage.

1. Add or edit a contact
2. Enter a country value containing a backslash (e.g. Sing\apore)
3. The input is accepted and the command succeeds

Image

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by hxckjian**
Change from `"^[a-zA-Z \\\\-]{1,50}$"` -> `"^[a-zA-Z -]{1,50}$"`
Closes #410
1 line of functional code changed

### CODE REVIEW

File: src/main/java/seedu/blockbook/model/gamer/Country.java [hunk 1]
```diff
@@ -14,7 +14,7 @@ public class Country {
             "Country should only contain letters, spaces, and hyphens, "
                     + "and be at most 50 characters.";
 
-    public static final String VALIDATION_REGEX = "^[a-zA-Z \\\\-]{1,50}$";
+    public static final String VALIDATION_REGEX = "^[a-zA-Z -]{1,50}$";
```
Comment (TehDrink) [inline src/main/java/seedu/blockbook/model/gamer/Country.java:17]: Looks good to go!

**Review by TehDrink — APPROVED** [review]
LGTM!
