### PR TITLE
[1.40] Fix `MESSAGE_USAGE` to include gamertag in format 2 in `find` command

### LINKED ISSUE #248: [1.40] `find` command is missing [gamertag/GAMERTAG] in format 2
gamertag/GAMERTAG optional param is missing in the MESSAGE_USAGE.

### PR DESCRIPTION
**Pull request by TehDrink**
Closes #248.

### CODE REVIEW

File: src/main/java/seedu/blockbook/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -25,8 +25,8 @@ public class FindCommand extends Command {
             + "\nFormat 1: " + COMMAND_WORD + " KEYWORD\n"
             + "\nFormat 1 example: " + COMMAND_WORD + " joe\n"
             + "\nSpecific attribute search is also available via Format 2 and can be stacked."
-            + "\nFormat 2: " + COMMAND_WORD + " [name/NAME] [phone/PHONE] [email/EMAIL] [group/GROUP]"
-            + " [server/SERVER] [favourite/FAVOURITE] [country/COUNTRY] [region/REGION] [note/NOTE]\n"
+            + "\nFormat 2: " + COMMAND_WORD + " [name/NAME] [gamertag/GAMERTAG] [phone/PHONE] [email/EMAIL]"
```
Comment (Jj910) [inline src/main/java/seedu/blockbook/logic/commands/FindCommand.java]:
```suggestion
            + "\nFormat 2: " + COMMAND_WORD + " [gamertag/GAMERTAG] [name/NAME] [phone/PHONE] [email/EMAIL]"
```
